name: nci
channels:
  - conda-forge
dependencies:
  - python
  - holoviews
  - bokeh
  - hvplot
  - panel
  - datashader
  - spatialpandas
  - holonote
  - numpy
  - pandas
  - xarray
  - scipy
  - ipykernel
  - jupyterlab
  - jupyter_bokeh
  - scanpy
  - anndata
  - python-igraph
  - leidenalg
  - pooch
  - scikit-image
  - sparse
  - decoupler-py
  - pip
  - pip:
     - git+https://github.com/holoviz-topics/hv-anndata.git@cf67907ad93ad80bd1652b6eae33095307a49dbb
