name: scanpy_holoviz
channels:
  - conda-forge
dependencies:
  - python
  - holoviews
  - bokeh
  - hvplot
  - panel
  - datashader
  - dask <2025.1.0
  - spatialpandas
  - numpy
  - pandas
  - scipy
  - ipykernel
  - jupyterlab
  - jupyter_bokeh
  - scanpy
  - anndata
  - python-igraph
  - leidenalg
  - pooch
  - scikit-image
  - xarray
  - sparse
  - decoupler-py
  - holonote
