name: cda_demo
channels:
  - conda-forge
dependencies:
  - python
  - holoviews
  - bokeh
  - hvplot
  - panel
  - datashader
  - spatialpandas
  - holonote
  - numpy
  - pandas
  - xarray
  - scipy
  - ipykernel
  - jupyterlab
  - jupyter_bokeh
  - google-cloud-bigquery
  - pip
  - pip:
    - pntables
    - git+https://github.com/CancerDataAggregator/cdapython.git